[FILTER]
    name modify
    match *
    add host ${HOSTNAME}

[FILTER]
    name record_modifier
    match *
    record cluster graylog-prod
    record environment linux

[FILTER]
    name modify
    match *
    copy log message
    copy MESSAGE message
