[OUTPUT]
    name gelf
    match !nginx.access
    host graylog.domain
    port 12201
    mode tcp
    gelf_short_message_key message
    gelf_full_message_key message
    gelf_host_key host
    retry_limit false
    storage.total_limit_size 1G

[OUTPUT]
    name                  gelf
    match                 nginx.access
    host                  graylog.sberins.ru
    port                  12201
    mode                  tcp
    gelf_short_message_key request
    gelf_host_key         host
