[SERVICE]
    flush 1
    daemon Off
    log_level info
    parsers_file parsers.conf
    storage.path /var/lib/fluent-bit/buffers
    storage.sync normal
    storage.checksum on
    storage.backlog.mem_limit 256M

# Общие filters/outputs
@INCLUDE common/*.conf

# Сервисные модули
@INCLUDE conf.d/enabled/*/*.conf
