[PARSER]
    Name        nginx3
    Format      regex
    Regex       ^(?<remote_addr>\S+) - (?<remote_user>\S+) \[(?<time_local>[^\]]+)\] "(?<request>[^"]+)" (?<status>\d+) (?<body_bytes_sent>\d+) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" "(?<hostname>[^"]*)"rt=(?<request_time>[0-9.]+) urt=(?<upstream_response_time>[0-9.-]+) uct=(?<upstream_connect_time>[0-9.]+) uht=(?<upstream_header_time>[0-9.]+) cs=(?<upstream_cache_status>\S+)
#    Regex       ^(?<remote_addr>\S+) - (?<remote_user>\S+) \[(?<time_local>[^\]]+)\] "(?<request>[^"]+)" (?<status>\d+) (?<body_bytes_sent>\d+) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" "(?<hostname>[^"]*)"
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
#    Time_Format %Y-%m-%d %H:%M:%S.%L
